require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'newproject' do
  use_unimodules!
  use_frameworks!

  config = use_native_modules!

  use_react_native!(
    :path => config["reactNativePath"],
    :hermes_enabled => true
  )

  target 'newprojectTests' do
    inherit! :complete
    # Pods for testing


    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  
    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  
    pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'
  
    pod 'react-native-video', :path => '../node_modules/react-native-video'
  
    pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'
  
    pod 'react-native-config', :path => '../node_modules/react-native-config'
  
    pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'
  
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  pod 'LyraPaymentSDK' , '1.2.1'
  pod 'ZXingObjC'

end

target 'newproject-tvOS' do
  # Pods for newproject-tvOS

  target 'newproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
